name: deploy_to_dev
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
  deploy:
    name: "deploy bundle to dev"
    runs-on: ubuntu-latest
    environment: dev
    steps:
        - uses: actions/checkout@v4
        - uses: databricks/setup-cli@main
        - run: databricks bundle deploy #--target dev --profile hellen_dev
          env:
                DATABRICKS_BUNDLE_ENV: dev
                DATABRICKS_HOST: ${{ secrets.HOST_DEV }}
                DATABRICKS_TOKEN: ${{ secrets.TOKEN_DEV }}
       