name: deploy_to_dev

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    name: "deploy bundle to dev"
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build + Databricks CLI (new)
        run: |
          python -m pip install -U pip build pipx
          python -m pipx ensurepath
          pipx install databricks
          databricks --version

      - name: Build wheel
        run: |
          rm -rf dist build *.egg-info
          python -m build
          ls -lah dist

      - name: Deploy bundle to dev
        env:
          DATABRICKS_HOST: ${{ secrets.HOST_DEV }}
          DATABRICKS_TOKEN: ${{ secrets.TOKEN_DEV }}
        run: |
          databricks bundle validate -t dev
          databricks bundle deploy -t dev
